### ISSUE TITLE
current value on calculator's output is reset to zero on every operation

### ISSUE THREAD

**Issue by princemuel** [princemuel/unocalc#11]
### Tasks

on this operation 6 + 2

Expected:

- [ ] when i click `6` then click `+`, the output should retain the 6
- [ ] when i click 2, the output updates to 2
- [ ] when i click `=`, the output updates to the result of the operation
