### ISSUE TITLE
properly document  the project

### ISSUE THREAD

**Issue by princemuel** [princemuel/unocalc#13]
### Tasks

- [ ] write the docs for each method, enum, struct and test in the Rust backend
- [ ] update the project's readme with the roadmap, and instructions on how to run and deploy the project
- [ ] update the project's readme with the with details about the projects e.g. features, tools used, resources used, pain points,, insights & discoveries, screenshots and acknowledgements
- [ ] update the project's repo issue list with issues encountered in the project
