### ISSUE TITLE
make the app a progressive web app

### ISSUE THREAD

**Issue by princemuel** [princemuel/unocalc#15]
### Tasks

- [x] add service worker 
- [x] add pwa assets with seo support
- [ ] enable offline caching
